version: '{build}'
os: unstable
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - .\make.cmd
test_script:
  - npm test
artifacts:
- path: '*.dll'
- path: test-output\**\*.png
